/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package superdemineur;

import java.util.Scanner;
import javax.swing.JButton;

/**
 *
 * @author Hugo
 */
public class FenetreJeu extends javax.swing.JFrame {

    
   
    Grille grilleDeJeu = new Grille();
    
    public FenetreJeu() {
        initComponents();
        panneau_grille.setVisible(false);
        panneau_infojoueur.setVisible(false);
        panneau_joueur1.setVisible(false);
        information.setVisible(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneau_joueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        debutant = new javax.swing.JButton();
        intermediaire = new javax.swing.JButton();
        expert = new javax.swing.JButton();
        information = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panneau_info = new javax.swing.JTextArea();
        panneau_infojoueur = new javax.swing.JPanel();
        lbl_kit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_joueur = new javax.swing.JLabel();
        lbl_pdv = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        panneau_joueur1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pseudo1 = new javax.swing.JTextPane();
        btn_start1 = new javax.swing.JButton();
        panneau_grille2 = new javax.swing.JPanel();
        panneau_grille3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(153, 153, 153));
        panneau_grille.setForeground(new java.awt.Color(255, 0, 51));
        panneau_grille.setLayout(new java.awt.GridLayout(8, 8));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 310, 240));

        panneau_joueur.setBackground(new java.awt.Color(102, 255, 255));
        panneau_joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SUPER DÉMINEUR :");
        panneau_joueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setText("Choisir un niveau de difficulté :");
        panneau_joueur.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        debutant.setText("Débutant");
        debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debutantActionPerformed(evt);
            }
        });
        panneau_joueur.add(debutant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, -1));

        intermediaire.setText("Intermédiaire");
        intermediaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intermediaireActionPerformed(evt);
            }
        });
        panneau_joueur.add(intermediaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, -1));

        expert.setText("Expert");
        expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expertActionPerformed(evt);
            }
        });
        panneau_joueur.add(expert, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 120, -1));

        getContentPane().add(panneau_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 260, 140));

        information.setBackground(new java.awt.Color(51, 255, 255));
        information.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel6.setText("INFORMATION JEU :");
        information.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        panneau_info.setColumns(20);
        panneau_info.setRows(5);
        jScrollPane2.setViewportView(panneau_info);

        information.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, 160));

        getContentPane().add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 430, 210, 220));

        panneau_infojoueur.setBackground(new java.awt.Color(102, 255, 255));
        panneau_infojoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_kit.setText("joueur_kit");
        panneau_infojoueur.add(lbl_kit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel3.setText("Points de vie :");
        panneau_infojoueur.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Kit de déminage : ");
        panneau_infojoueur.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        jLabel5.setText("Joueur :");
        panneau_infojoueur.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lbl_joueur.setText("nomjoueur");
        panneau_infojoueur.add(lbl_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        lbl_pdv.setText("joueur_pdv");
        panneau_infojoueur.add(lbl_pdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        l.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        l.setText("INFORMATION JOUEUR :");
        panneau_infojoueur.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, -1));

        getContentPane().add(panneau_infojoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 220, 170));

        panneau_joueur1.setBackground(new java.awt.Color(102, 255, 255));
        panneau_joueur1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Pseudo Joueur :");
        panneau_joueur1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane3.setViewportView(pseudo1);

        panneau_joueur1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 70, -1));

        btn_start1.setText("Commencer");
        btn_start1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_start1ActionPerformed(evt);
            }
        });
        panneau_joueur1.add(btn_start1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        getContentPane().add(panneau_joueur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 220, 80));

        panneau_grille2.setBackground(new java.awt.Color(102, 102, 102));
        panneau_grille2.setLayout(new java.awt.GridLayout(16, 16));
        getContentPane().add(panneau_grille2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 530, 410));

        panneau_grille3.setBackground(new java.awt.Color(204, 204, 204));
        panneau_grille3.setLayout(new java.awt.GridLayout(22, 22));
        getContentPane().add(panneau_grille3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 700, 600));

        setBounds(0, 0, 1030, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_start1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_start1ActionPerformed
panneau_infojoueur.setVisible(true);
        information.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        panneau_grille2.repaint();
        panneau_grille3.repaint();
        btn_start1.setEnabled(false);
    }//GEN-LAST:event_btn_start1ActionPerformed

    private void debutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debutantActionPerformed
        panneau_grille2.setVisible(false);
        panneau_grille3.setVisible(false);
        panneau_joueur1.setVisible(true);
        for (int i=7; i>=0 ; i--) {
            for (int j=0; j<8 ; j++) {
                CelluleGraphique cellgraph = new CelluleGraphique(grilleDeJeu.Cellules[i][j]);
                panneau_grille.setVisible(true);
                panneau_grille.add(cellgraph);
            }
        }
    }//GEN-LAST:event_debutantActionPerformed

    private void intermediaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intermediaireActionPerformed
        panneau_grille.setVisible(false);
        panneau_grille3.setVisible(false);
        panneau_joueur1.setVisible(true);
            for (int i=15; i>=0 ; i--) {
            for (int j=0; j<16 ; j++) {
                CelluleGraphique cellgraph = new CelluleGraphique(grilleDeJeu.Cellules[i][j]);
                panneau_grille2.setVisible(true);
                panneau_grille2.add(cellgraph);
            }
            }
    }//GEN-LAST:event_intermediaireActionPerformed

    private void expertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expertActionPerformed
        panneau_grille.setVisible(false);
        panneau_grille2.setVisible(false);
        panneau_joueur1.setVisible(true);
            for (int i=21; i>=0 ; i--) {
            for (int j=0; j<22 ; j++) {
                CelluleGraphique cellgraph = new CelluleGraphique(grilleDeJeu.Cellules[i][j]);
                panneau_grille3.setVisible(true);
                panneau_grille3.add(cellgraph);
            }
            }
    }//GEN-LAST:event_expertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreJeu().setVisible(true);
            }
        });
    }
void initialiserPartie() {
        int choix;
        
        //Création du joueur
        String nomJoueur =  pseudo1.getText();
        Joueur J1 = new Joueur(nomJoueur,3); //joueur sans pseudo avc 3PV
        System.out.println("Milestone1");
        lbl_joueur.setText(nomJoueur);
        lbl_pdv.setText(J1.pointDeVie+"");
        lbl_kit.setText(J1.nbKit+"");
        choix = choixmenu();
        System.out.println("Milestone2");
        //on definit le coté en fonction du choix
        valeurcoté(choix);
        System.out.println("Milestone3");
        // on définit le nb de mine en fonction du choix
        nombreMines(choix);
        System.out.println("Milestone4");
        // on definit le nb de Kit en fonction du choix
        nombreKits(choix);
        System.out.println("Milestone5");
        // on place les mines dans la grille
        grilleDeJeu.répartitionMine();// a adapter a la grille dyna
        System.out.println("Milestone6");
        // on place les Kits dans la grille
        grilleDeJeu.répartitionKit(); // a adapter a la grille dyna
        System.out.println("Milestone7");
       	// on attribue les proximines
        grilleDeJeu.PlacerProxi();// a adapter a la grille dyna
        System.out.println("Milestone8");
        // on affiche la grille
        grilleDeJeu.afficherGrillesurConsole();// a adapter a la grille dyna
    }


int choixmenu() {
    int choix=0;
    if (debutant != null) {
            choix = 1;
           } else if(intermediaire != null){
            choix = 2;
        } else if(expert != null){
            choix = 3;
        }
    return choix;
}

void nombreMines (int cho_ix){ // nb de mine en fonction du mode 
    if (cho_ix==1){
        grilleDeJeu.nombremines=10;
    }else{
        if (cho_ix==2){
            grilleDeJeu.nombremines=40;
        }else{
            if(cho_ix==3){
                grilleDeJeu.nombremines=99;
            }
        }
    }
}

void nombreKits (int cho_ix){ // nb de KIT en fonction du mode 
    if (cho_ix==1){
        grilleDeJeu.nombrekits=4;
    }else{
        if (cho_ix==2){
            grilleDeJeu.nombrekits=15;
        }else{
            if(cho_ix==3){
                grilleDeJeu.nombrekits=33;
            }
        }
    }
}
void valeurcoté (int ch_oix){ // dimensions de la grille en fonction du mode (grille carrée) 
    if (ch_oix==1){ //grille 8x8 = 64cases, 420 (nice) cases en moins
        grilleDeJeu.coté=8;
    }else{
        if (ch_oix==2){ //grille 16x16=256, 228cases en moins
            grilleDeJeu.coté=16;
        }else{
            if(ch_oix==3){ //grille 22x22 par défaut= 484cases
                grilleDeJeu.coté=22;
            }
        }
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start1;
    private javax.swing.JButton debutant;
    private javax.swing.JButton expert;
    private javax.swing.JPanel information;
    private javax.swing.JButton intermediaire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel l;
    private javax.swing.JLabel lbl_joueur;
    private javax.swing.JLabel lbl_kit;
    private javax.swing.JLabel lbl_pdv;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_grille2;
    private javax.swing.JPanel panneau_grille3;
    private javax.swing.JTextArea panneau_info;
    private javax.swing.JPanel panneau_infojoueur;
    private javax.swing.JPanel panneau_joueur;
    private javax.swing.JPanel panneau_joueur1;
    private javax.swing.JTextPane pseudo1;
    // End of variables declaration//GEN-END:variables
}
